# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4f66394732606cd242d15a6fa1165a5bceb5765ea231d3e404fe1754898de003028f9df36de9c99344962776d6c061d9ec205bfef2effee3dea2670156ac4e7

test:
  secret_key_base: 9f74764c956e4a1f9207583d236bcd31ef8923390f546f3b609c3b4144877b7835d5f28c467f6d4d1ea77bda1c11a14988387002d730b134425578fbcea4958c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
